language: node_js
node_js:
- '8'
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
addons:
  chrome: stable
  firefox: "latest"
  sonnarcloud:
    organization: "sytw2019"
    token:
      secure: "Mb0r8CqRo+Dkv9e+Ye5JHHtZGBIkE5roymIRJpckxIOPPLDc2a32anQaI+2gVFyao15OrGHslyefkgdsBTRJC3wPGCleMUglo6gVC8iYNLU0SVdZZixyFvVLFlZZpnD1TBAke0Z4A4pEUF51j0gBzpkLRVJKWuJ/3bSa5F1CMz17pHaNBztxTjzAOwRnhaLEgCXu+51lFSmmeP6rKK9jH6EU5ZMId5tQl2d7o6zybI5cP114J08Yyf/OZ5h1TR9eGy+tb8DADaprJw/sUBIMLXXuhPbkIFfTeVsfGyLHVwq/YvG+HbrV2GrpWUQ6tY7CWYT8wwWxvEjz1mliJqDM544j+fwGPp7qgeHTlo3DqAgSd4oRfq2XY7cEBBpd64ZQgM7vILVbp+AwJAAVCFV6frqDQQU6lptIwZigPpfAzrUJlnQXPmYWE0QDzk97GnSPfGjPqrguc38vy6AtJGdpnI93131N1TLlOMi7cTsRopTF6hXxGR8D3yKnjhQMC0kYm0bh+UtwcHfR0ddGzep1F64epQG891dYmxvJV/OuOZuR/IaqMkMIYH1AYDxKCqUWX1RNfwsvZic6Is2ARGZ655XXhuYo3syXcW1tAjutNX+IsBfsyiGAipAli3pw+uh0l1OyvwVGk/7VLjrZV+n06+aznNLniR2YjxUQ7Hug3Kw="
beforescript:
- "export DISPLAY=:99.0"
- sh -e /etc/init.d/xvfb start
- nohup bash -c "./node_modules/protractor/bin/webdriver-manager start 2>&1 &"
- sleep 5
script:
- cd angular-src
- npm install
- node node_modules/protractor/bin/webdriver-manager update
- ng e2e
- cd ..
- sonnar-scanner
notifications:
  slack:
    matrix:
    - "<sytw>:<GUjDz0vvrkI1dqBHhx0Kh3Xy>#2019-e01"
    rooms:
      secure: rckEwR+3KmNQukURES97PYuyz6V0Wefq0J5G4MZRvLQu786d0tItlBQ0he9er+eEKrVjtVWZiDZayx40SZni7BOuc3dfMhvxQlP3tLfquIBPTTzqk0CCn4XtN4Dt+kR2CcR3jMNP5vH0ZpXsOvKyy5WlFshgbqZM5MHLQMTb6FFFiq6dTWEtykhCH6B0i69VGk1xaAcTt2Z4IO66ZYSiQziEYucB3io0POMzwbNurQ/8UqL0IJ0wlaxlV0jGhQ/JpFX2kSyLFhPu5FXNYW41/NvamdEyWp1TvWgM5tSXmD/QMaV7ZnRlXbPlc19hzHHt9EmUd5vH8QBocqt14alfEJs2yC270FtMUqSKLlAr5cWWddUm3E53tm/QEYHYUzHpxn92jW2oC7k5Zo3LCjtq5bq5llhnMFvXhbq4jkBBOR7tbKJBucPHS1IfiipdSy2RO1ddpb58EmKT7yCnELvchz9nmCW9PZ0dBui5/FFhMmb/t4nZehQxQuIfpCVVjKrP1yWEODQhLbn5sNvG3BO12k6pAJdNKYG302LZB/Btg6BTdCzgw4Ij6ZxEcArrcPKth0JNzDl7TpAuBEMc6AALPdGm3V0LwDn3cvSaho+CJ/O5/3ZCq60xPIBNmx4840WmsukWCo0FOYguv6Wkkf5+REn8lHOxitJ9jDxFp4b7nEs=
