language: node_js
node_js:
- '8'
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
addons:
  chrome: stable
  firefox: "latest"
  sonnarcloud:
    organization: "sytw2019"
    token:
      secure: "CJGDAnsbo8H2KWy9SBa9QiBQ8F8JXNBVcSTAM3Q6iQI3rC9foNzkS+xtpl8IE2hInJEe97Or74e6VYndglXjarqdqcAo4v9FGQ+E1+cwcM6seF3tTloqKnYz3DyOSX//BfGdAfOruA+knEKTRYfAwGj+CL9rGNZ0SYwBUiN4qrofaFt5ZBdkHlznfw5MsndFb8vG68nRrkOyYmCuJXlRvO21FDGES/T2aLelVELRQvG5gmxSFCDOJfpk3IxE3r1MKXKyr80pmSTEvT7pFufsgG8i5I4YXSBA9o4UVywo2/sSVeuoa3DmAfEl3RLePsrUDTRBDmlTfpcDV9jblhnc8IpS4OjBXC7L1zaIiW0pV3bqLbdbVmBWEQGo4KQTfJdL+RhFe36K+vmfV69O4Tqi17ca34V7c30oLoBeCb2b/BbwrlE014j6OoBGDDsI+9eIgUjqglTcUKWkCfpW34FjZu3K5oDcLTj+Bm6UarRv7aNzaBFFctWGWfpIoV9mhu16VRpmzC5gDbs6JoAQYJfZYyuCEabBqQQYZoGSp3SRaT52d/DfLMqFAYR/JaUh7KggKKXG76GpItiZejqFb5GUHVEbGTUM2Zx+qF2PUWih4magRke07byJFIPQDXLEkOAvt0pVGKMiPngiLpnByTra52DHrNcUILQwaWLIusT77Go="
beforescript:
- "export DISPLAY=:99.0"
- sh -e /etc/init.d/xvfb start
- nohup bash -c "./node_modules/protractor/bin/webdriver-manager start 2>&1 &"
- sleep 5
script:
- cd angular-src
- npm install
- node node_modules/protractor/bin/webdriver-manager update
- ng e2e
- cd ..
- npm i sonarqube-scanner
- sonar-scanner
notifications:
  slack:
    matrix:
    - "<sytw>:<GUjDz0vvrkI1dqBHhx0Kh3Xy>#2019-e01"
    rooms:
      secure: rckEwR+3KmNQukURES97PYuyz6V0Wefq0J5G4MZRvLQu786d0tItlBQ0he9er+eEKrVjtVWZiDZayx40SZni7BOuc3dfMhvxQlP3tLfquIBPTTzqk0CCn4XtN4Dt+kR2CcR3jMNP5vH0ZpXsOvKyy5WlFshgbqZM5MHLQMTb6FFFiq6dTWEtykhCH6B0i69VGk1xaAcTt2Z4IO66ZYSiQziEYucB3io0POMzwbNurQ/8UqL0IJ0wlaxlV0jGhQ/JpFX2kSyLFhPu5FXNYW41/NvamdEyWp1TvWgM5tSXmD/QMaV7ZnRlXbPlc19hzHHt9EmUd5vH8QBocqt14alfEJs2yC270FtMUqSKLlAr5cWWddUm3E53tm/QEYHYUzHpxn92jW2oC7k5Zo3LCjtq5bq5llhnMFvXhbq4jkBBOR7tbKJBucPHS1IfiipdSy2RO1ddpb58EmKT7yCnELvchz9nmCW9PZ0dBui5/FFhMmb/t4nZehQxQuIfpCVVjKrP1yWEODQhLbn5sNvG3BO12k6pAJdNKYG302LZB/Btg6BTdCzgw4Ij6ZxEcArrcPKth0JNzDl7TpAuBEMc6AALPdGm3V0LwDn3cvSaho+CJ/O5/3ZCq60xPIBNmx4840WmsukWCo0FOYguv6Wkkf5+REn8lHOxitJ9jDxFp4b7nEs=
