language: node_js
dist: trusty
sudo: false
node_js:
- stable
cache:
  directories:
  - node_modules
addons:
  chrome: stable
  firefox: "latest"
  sonarcloud:
    organization: "sytw2019"
    token:
      secure: "FxRqniDuoIO3BRKeQV84WQ7tE2t5pbU0/rT4Xa6nFO/8dlDUjSBmNAn2Osfl6sO6YSomvhuEqZ4Z5O6NsGMXaQ0nisrzPlWFKIf7QiW+Cbhvz1ZinhPXvdv3cHNlmw/aE5nUFKoJMua3F2Dyu8LogsMqRtLN+LoDJ1ST1TTxZhud7oSTj3B/3ezxRymU/V8MEvNlCW7Oh85YkS1MDvd8w3RBbQAi/mQdaRar6zBZIl/YPY/fsvvRgCqMyMsvSL8OzmvL45LieRRf07tapd5oWUHwT4a1Ol0GfZ0NBubALTyvR5s3jY4PSUsTOiVBJ5GPvVNvGqIFt1KDpMu2joYkR8/80580urOTUQNIJ4xLNn4CfqXCCXxmaPjKkLIsFuPysp1HBKqTbE+kJruHVJBDadQ1r5eoJTL7tFmJkpFCHxElIoci2le8QOpIO6f+P/zwN6EWT0EmvwDJ4Zx/usV6/eadzMAhXypDnRIKPxTFCtz0416EILWn57FMyrqTZbg+NAKnaNbbMC2cyhGKps22J6O+plJ/mtyWOt4w+F8hO1apx3Ih+wOx3Kd0UPgrF+CksB+RqQJJ8tEqbjejsKisGnTY7lGQx4+Xobfrvoj4gSg8Vq2gd/68n5OjAgo9PUloW5mLse58qRi9EAksR1/DzmRBeRO+5dbonYoouNOkTRI="     
beforescript:
- "export DISPLAY=:99.0"
- sh -e /etc/init.d/xvfb start
- nohup bash -c "./node_modules/protractor/bin/webdriver-manager start 2>&1 &"
- sleep 5
script:
- cd angular-src
- npm install
- node node_modules/protractor/bin/webdriver-manager update
- ng e2e
#- cd ..
- sonar-scanner
notifications:
  slack:
    matrix:
    - "<sytw>:<GUjDz0vvrkI1dqBHhx0Kh3Xy>#2019-e01"
    rooms:
      secure: rckEwR+3KmNQukURES97PYuyz6V0Wefq0J5G4MZRvLQu786d0tItlBQ0he9er+eEKrVjtVWZiDZayx40SZni7BOuc3dfMhvxQlP3tLfquIBPTTzqk0CCn4XtN4Dt+kR2CcR3jMNP5vH0ZpXsOvKyy5WlFshgbqZM5MHLQMTb6FFFiq6dTWEtykhCH6B0i69VGk1xaAcTt2Z4IO66ZYSiQziEYucB3io0POMzwbNurQ/8UqL0IJ0wlaxlV0jGhQ/JpFX2kSyLFhPu5FXNYW41/NvamdEyWp1TvWgM5tSXmD/QMaV7ZnRlXbPlc19hzHHt9EmUd5vH8QBocqt14alfEJs2yC270FtMUqSKLlAr5cWWddUm3E53tm/QEYHYUzHpxn92jW2oC7k5Zo3LCjtq5bq5llhnMFvXhbq4jkBBOR7tbKJBucPHS1IfiipdSy2RO1ddpb58EmKT7yCnELvchz9nmCW9PZ0dBui5/FFhMmb/t4nZehQxQuIfpCVVjKrP1yWEODQhLbn5sNvG3BO12k6pAJdNKYG302LZB/Btg6BTdCzgw4Ij6ZxEcArrcPKth0JNzDl7TpAuBEMc6AALPdGm3V0LwDn3cvSaho+CJ/O5/3ZCq60xPIBNmx4840WmsukWCo0FOYguv6Wkkf5+REn8lHOxitJ9jDxFp4b7nEs=