language: node_js
dist: trusty
sudo: false
node_js:
- stable
cache:
  directories:
  - node_modules 
beforescript:
- "export DISPLAY=:99.0"
- sh -e /etc/init.d/xvfb start
- nohup bash -c "./node_modules/protractor/bin/webdriver-manager start 2>&1 &"
- sleep 5
script:
- cd angular-src
- npm install
- node node_modules/protractor/bin/webdriver-manager update
- ng e2e
- cd ..
- sonar-scanner
notifications:
  slack:
    matrix:
    - "<sytw>:<GUjDz0vvrkI1dqBHhx0Kh3Xy>#2019-e01"
    rooms:
      secure: rckEwR+3KmNQukURES97PYuyz6V0Wefq0J5G4MZRvLQu786d0tItlBQ0he9er+eEKrVjtVWZiDZayx40SZni7BOuc3dfMhvxQlP3tLfquIBPTTzqk0CCn4XtN4Dt+kR2CcR3jMNP5vH0ZpXsOvKyy5WlFshgbqZM5MHLQMTb6FFFiq6dTWEtykhCH6B0i69VGk1xaAcTt2Z4IO66ZYSiQziEYucB3io0POMzwbNurQ/8UqL0IJ0wlaxlV0jGhQ/JpFX2kSyLFhPu5FXNYW41/NvamdEyWp1TvWgM5tSXmD/QMaV7ZnRlXbPlc19hzHHt9EmUd5vH8QBocqt14alfEJs2yC270FtMUqSKLlAr5cWWddUm3E53tm/QEYHYUzHpxn92jW2oC7k5Zo3LCjtq5bq5llhnMFvXhbq4jkBBOR7tbKJBucPHS1IfiipdSy2RO1ddpb58EmKT7yCnELvchz9nmCW9PZ0dBui5/FFhMmb/t4nZehQxQuIfpCVVjKrP1yWEODQhLbn5sNvG3BO12k6pAJdNKYG302LZB/Btg6BTdCzgw4Ij6ZxEcArrcPKth0JNzDl7TpAuBEMc6AALPdGm3V0LwDn3cvSaho+CJ/O5/3ZCq60xPIBNmx4840WmsukWCo0FOYguv6Wkkf5+REn8lHOxitJ9jDxFp4b7nEs=
addons:
  chrome: stable
  firefox: "latest"
  sonarcloud:
    organization: "sytw2019"
    token:
      secure: "xBdCORD0DAkIOlK3oPF+ZWkrjlKftTz+LzbEs0/0e/dvKAwUZqB6+VVGXXD3SxoGanDrhBSceRikvqsnjMM7WMKk0WosqLa6Ru4v8PTX7NAJZj5cGeBnA2QqdomTQ4GYHrV6OdKhzssX2jI8LtgblQIZtPXd1Jjx51Ss3iiKU7Et1UJECJ1gBXdLwHO923jQpO36Ix8UOXFm8+XukqZTNLCuKjAxxQ4JDnYaptbPgZquh4WOD/cup0FiMNIbP2mOOpRlKPqo8mZNrKi0N/Z4D+a2s3WiC9rNO9Mn86OZwGe6l4Sedse+zcyOD+8z36txnKOnXI83xYplBrdMkrlHh9I7sAVG//a9TBoBLQ2jXLYNLYj16QscrwNzUfpoTt+SkZMV1Ive3zlX1dFWC+51g2nSzt5l3WlxJzDk7IwdiqbKIhdsMUdd1LqImND3a/jhJaDtFI7Kv97uuldR1d66e1isayzOPgoGaNkVxd/SLTltRnlg+gnoZQpwIPdaeLoVA1ED6QfCWwkFpUXUQw+T6xd+c8Gigxp1LZa7HX5whYe8WVUhViadlI+pniXmQt6g2p6NcJysIQPRNV7A6A7LGGyng0CiqHf12DJUSFBhE1glVGBJmDlm4RvxaQevtHjDTI7KULHjQille0g+tfYGpoWOWE5KpTuUo4qH5eazLMA="   